-- ====================================================================
-- schema.sql v0.2.3 · 2026-04-24 · corresponds to spec.md v0.3.0
-- ====================================================================
-- PI Briefing Console · v0.1 · Postgres 16 self-host · single lab
--
-- Table count: 15 (original 12 + llm_calls + R1 paper_summaries + R1 export_log)
--   Note: architecture.md §5 "original 12 → 14" narrative is a counter
--   drift; the enumerated table list is the authoritative 15. The
--   15 tables match T003.md Outputs `src/db/schema.ts` exactly.
--
-- File-level changelog:
--   2026-04-23 v0.2.1: initial authoritative DDL (15 tables).
--   2026-04-24 v0.2.2: F5 pre-R_final hardening · paper_summaries.llm_call_id
--     changed from NOT NULL / ON DELETE RESTRICT to NULL / ON DELETE SET NULL
--     to support JSON export round-trip (api-contracts.md §3.11 option (a)).
--     No other DDL changes; header bump aligns with spec.md v0.2.2.
--   2026-04-24 v0.2.3: R_final BLOCK fix G1 · rewrite paper_summaries
--     `summary_sentence_cap` CHECK from "split on terminator+whitespace"
--     to "count terminator occurrences" (English `.!?` + Chinese `。！？`).
--     Correctly handles pure Chinese text with no whitespace between
--     sentences; rejects zero-terminator strings. No other DDL changes.
--
-- Authoritative references:
--   - specs/001-pA/architecture.md §5 (ER diagram + per-table fields)
--   - specs/001-pA/tasks/T003.md (schema inventory + R1 additions)
--   - specs/001-pA/spec.md §4 (D15 summary_sentence_cap, D16 skip_requires_why)
--   - specs/001-pA/reference/api-contracts.md §3.11 (F5 round-trip policy)
--
-- Coding conventions:
--   - snake_case for all identifiers
--   - timestamps are `timestamptz`; `created_at` default `now()`
--   - ON DELETE CASCADE is used when child row is meaningless
--     without parent (breadcrumbs → resurface_events; papers →
--     paper_summaries); ON DELETE RESTRICT is used when deletion
--     implies a bug (labs → topics; labs → seats).
--   - bigserial primary keys for tables with potentially unbounded
--     row count (papers / actions / llm_calls / ...); smallserial for
--     seat-scoped bounded tables (seats / topics).
--
-- Apply procedure (dev):
--   createdb pi_briefing
--   psql -d pi_briefing -f schema.sql
--
-- Apply procedure (prod):
--   do NOT run this file directly in prod. Prod uses
--   `src/db/migrations/0000_initial.sql` generated by drizzle-kit;
--   this file is the human-readable authoritative DDL for reviews
--   and break-glass restoration only. CI enforces no drift between
--   the two via `drizzle-kit generate` + diff (see
--   reference/directory-layout.md §9 CI pipeline).
-- ====================================================================


-- --------------------------------------------------------------------
-- DANGER zone · dev-only teardown (commented out)
-- --------------------------------------------------------------------
-- Uncomment the block below to wipe and recreate from scratch. Never
-- run this in production; it will drop every table and every row.
-- --------------------------------------------------------------------
-- drop table if exists export_log cascade;
-- drop table if exists paper_summaries cascade;
-- drop table if exists llm_calls cascade;
-- drop table if exists fetch_runs cascade;
-- drop table if exists briefings cascade;
-- drop table if exists resurface_events cascade;
-- drop table if exists breadcrumbs cascade;
-- drop table if exists actions cascade;
-- drop table if exists paper_topic_scores cascade;
-- drop table if exists paper_citations cascade;
-- drop table if exists papers cascade;
-- drop table if exists topics cascade;
-- drop table if exists sessions cascade;
-- drop table if exists seats cascade;
-- drop table if exists labs cascade;


-- --------------------------------------------------------------------
-- Extensions (none required for v0.1)
-- --------------------------------------------------------------------
-- pgvector intentionally NOT installed (OUT-4 in spec.md §2.2).
-- No FTS extension either; Postgres built-in tsvector is unused in v0.1.


-- ====================================================================
-- 1. labs · tenant boundary (single-lab deploy in v0.1)
-- ====================================================================
-- One row per deployment. v0.1 keeps a single row for the dogfood lab.
-- `first_day_at` is the anchor used by the day-30 sentinel (T026);
-- `allow_continue_until` is set by the operator during the 7-day
-- escalate-banner override window (see spec.md §6 Sentinel).
-- ====================================================================
create table if not exists labs (
  id                    bigserial       primary key,
  name                  text            not null,
  -- R1 additions (T003 R1-c); used by day-30 sentinel (T026) to
  -- compute `since_day` and to record operator's signed override.
  first_day_at          timestamptz     not null default now(),
  allow_continue_until  timestamptz     null,
  created_at            timestamptz     not null default now()
);


-- ====================================================================
-- 2. seats · lab members (≤ 15 rows; C9)
-- ====================================================================
-- Each row is a login identity bound to a lab. `role` gates admin
-- capabilities (topic CRUD, invite, export). `invite_token_hash` is
-- the sha256 of the one-time invite token emitted by admin; it is
-- cleared to null once consumed (enforced by T006 consumeInvite()).
-- `invite_expires_at` enforces the 24h TTL from spec.md §7.
-- ====================================================================
create table if not exists seats (
  id                    bigserial       primary key,
  lab_id                bigint          not null
                        references labs(id) on delete restrict,
  email                 text            not null,
  role                  text            not null,
  -- R1→R2 Q2 auth columns (T003 R2-a · pre-loaded here so T006
  -- does not need its own migration). `invite_token_hash` stores
  -- sha256(plain token); plain token exists only in the email/URL
  -- handed to the invited user. Nulls mean "no pending invite".
  invite_token_hash     text            null,
  invite_expires_at     timestamptz     null,
  invited_at            timestamptz     null,
  last_login_at         timestamptz     null,
  created_at            timestamptz     not null default now(),

  -- One identity per (lab, email) pair; O1/O3 queries dedupe by this.
  constraint seats_lab_email_unique       unique (lab_id, email),
  constraint seats_role_enum              check (role in ('admin', 'member'))
);

-- UNIQUE partial index on invite_token_hash for lookup + rejection
-- of duplicate unconsumed tokens (only enforced when token is set).
create unique index if not exists seats_invite_token_hash_uniq
  on seats (invite_token_hash)
  where invite_token_hash is not null;


-- ====================================================================
-- 3. sessions · login session store (JWT hash lookup + revocation)
-- ====================================================================
-- Each row tracks one successful login. `token_hash` is the sha256 of
-- the JWT (JWT itself stays in the httpOnly cookie, never in DB).
-- `login_date` is redundant (= issued_at::date) but kept as a covered
-- column on `(seat_id, login_date)` index for O1/O3 queries.
-- `revoked_at` enables server-side logout / admin-forced kick
-- (auth middleware asserts `revoked_at IS NULL`).
-- `last_active_at` is bumped on every authenticated request for
-- sliding expiry and bus-factor sentinel (BUS-1).
-- ====================================================================
create table if not exists sessions (
  id                    bigserial       primary key,
  seat_id               bigint          not null
                        references seats(id) on delete cascade,
  token_hash            text            not null,
  issued_at             timestamptz     not null default now(),
  expires_at            timestamptz     not null,
  login_date            date            not null, -- redundant for index
  ip                    text            null,
  user_agent            text            null,
  -- R1→R2 Q2 auth columns (T003 R2-a).
  revoked_at            timestamptz     null,
  last_active_at        timestamptz     not null default now(),

  constraint sessions_token_hash_uniq unique (token_hash)
);

-- Hot index for day-active queries (O1 · PI 25/30; O3 · operator ≥2/wk).
create index if not exists sessions_seat_login_date_idx
  on sessions (seat_id, login_date);

-- Used by operator-absence sentinel (BUS-1) and by session lookup.
create index if not exists sessions_seat_last_active_idx
  on sessions (seat_id, last_active_at);


-- ====================================================================
-- 4. topics · lab-owned topic pool (8–15 active; IN-1)
-- ====================================================================
-- `keyword_pool`, `arxiv_categories`, `seed_authors` are `text[]`
-- rather than jsonb because all three are flat string lists and we
-- want native GIN index + array operators. `archived_at` soft-
-- deletes a topic (keeps history for papers already matched; UI
-- filters `where archived_at is null`).
-- ====================================================================
create table if not exists topics (
  id                    bigserial       primary key,
  lab_id                bigint          not null
                        references labs(id) on delete restrict,
  name                  text            not null,
  keyword_pool          text[]          not null default '{}',
  arxiv_categories      text[]          not null default '{}',
  seed_authors          text[]          not null default '{}',
  created_by_seat_id    bigint          null
                        references seats(id) on delete set null,
  created_at            timestamptz     not null default now(),
  updated_at            timestamptz     not null default now(),
  archived_at           timestamptz     null
);

create index if not exists topics_lab_id_idx on topics (lab_id);
create index if not exists topics_keyword_pool_gin
  on topics using gin (keyword_pool);
create index if not exists topics_arxiv_categories_gin
  on topics using gin (arxiv_categories);


-- ====================================================================
-- 5. papers · global arXiv paper table (deduped by arxiv_id)
-- ====================================================================
-- Shared across labs in principle (there's no lab_id column) because
-- arXiv data is public and deduplicating avoids re-fetch cost. In
-- v0.1 only a single lab is deployed, but keep the design so v0.2
-- federation can add `lab_id` without backfill. `fetched_at` is when
-- the worker pulled from arXiv (distinct from `published_at`).
-- No PDF storage (OUT-6).
-- ====================================================================
create table if not exists papers (
  id                    bigserial       primary key,
  arxiv_id              text            not null,
  title                 text            not null,
  abstract              text            not null,
  authors               text[]          not null default '{}',
  categories            text[]          not null default '{}',
  primary_category      text            null,
  published_at          timestamptz     not null,
  fetched_at            timestamptz     not null default now(),

  constraint papers_arxiv_id_uniq unique (arxiv_id)
);

create index if not exists papers_published_at_idx on papers (published_at);
create index if not exists papers_categories_gin
  on papers using gin (categories);


-- ====================================================================
-- 6. paper_citations · citation graph edges
-- ====================================================================
-- One row per (citing paper → cited arxiv_id). `cited_arxiv_id` is a
-- text string (not FK) because the referenced paper may not yet be
-- in `papers` (arXiv references can point to papers we haven't
-- ingested). See T003 Known gotchas.
-- Hot-path index supports citation-triggered resurface (spec §4.2):
-- given a new paper's reference list, find which breadcrumbs cite
-- it in O(log N). In v0.1 we keep raw arxiv_id rather than resolve
-- to `papers.id` to preserve the reference record when the referent
-- is missing from our corpus.
-- ====================================================================
create table if not exists paper_citations (
  citing_paper_id       bigint          not null
                        references papers(id) on delete cascade,
  cited_arxiv_id        text            not null,
  discovered_at         timestamptz     not null default now(),

  primary key (citing_paper_id, cited_arxiv_id)
);

-- Hot path: citation-triggered resurface lookup.
create index if not exists paper_citations_cited_arxiv_idx
  on paper_citations (cited_arxiv_id);


-- ====================================================================
-- 7. paper_topic_scores · matcher results (paper ↔ topic)
-- ====================================================================
-- One row per (paper, topic) match. `match_signal` records why the
-- paper was pulled into the topic (keyword hit, arXiv category
-- overlap, or seed author hit). A paper may belong to multiple
-- topics (one row per topic).
-- ====================================================================
create table if not exists paper_topic_scores (
  paper_id              bigint          not null
                        references papers(id) on delete cascade,
  topic_id              bigint          not null
                        references topics(id) on delete cascade,
  match_signal          text            not null,
  matched_keywords      jsonb           not null default '[]'::jsonb,
  score                 double precision null,
  computed_at           timestamptz     not null default now(),

  primary key (paper_id, topic_id),
  constraint paper_topic_scores_signal_enum
    check (match_signal in ('keyword', 'category', 'seed_author'))
);

-- Hot path: daily worker joins by topic_id to build per-topic candidates.
create index if not exists paper_topic_scores_topic_idx
  on paper_topic_scores (topic_id);


-- ====================================================================
-- 8. actions · 4-action records (per seat × per paper; D4 fixed set)
-- ====================================================================
-- Each row is one annotation by a seat on a paper. `action` is the
-- closed enum `{read_now, read_later, skip, breadcrumb}` (D4). `why`
-- is a short free-text explanation.
--
-- RED LINE 2 mechanical enforcement (Layer 1 of 3; D16, ADR-7):
--   constraint `skip_requires_why` rejects any insert where
--   action='skip' and the `why` field (after btrim) is shorter
--   than 5 characters. Layers 2 and 3 live in the API
--   (src/lib/actions/recordAction.ts) and UI
--   (src/components/skip-why-input.tsx) respectively — any single
--   layer being bypassed is still caught by the remaining layers.
-- ====================================================================
create table if not exists actions (
  id                    bigserial       primary key,
  seat_id               bigint          not null
                        references seats(id) on delete cascade,
  paper_id              bigint          not null
                        references papers(id) on delete cascade,
  action                text            not null,
  why                   text            null,
  created_at            timestamptz     not null default now(),

  constraint actions_action_enum
    check (action in ('read_now', 'read_later', 'skip', 'breadcrumb')),
  -- Max 280 chars on any why text (spec §IN-3 / §4.1).
  constraint actions_why_length
    check (why is null or char_length(why) <= 280),
  -- RED LINE 2 · D16 Layer 1: skip is only valid if why has ≥ 5
  -- non-whitespace characters. See ADR-7 for rationale, TECH-8/9
  -- for Chinese char-count edge cases.
  constraint skip_requires_why
    check (
      action != 'skip' or
      (why is not null and char_length(btrim(why)) >= 5)
    )
);

-- Hot path: O3/O4 per-seat action audits and /papers/:id/history.
create index if not exists actions_seat_created_idx
  on actions (seat_id, created_at);
create index if not exists actions_paper_idx
  on actions (paper_id);


-- ====================================================================
-- 9. breadcrumbs · active breadcrumb tracking (resurface source)
-- ====================================================================
-- Written synchronously alongside `actions` whenever a seat picks
-- `action='breadcrumb'`, so the resurface scheduler can scan this
-- table without joining `actions`. Once a breadcrumb is dismissed,
-- `dismissed_at` is set and it no longer triggers resurface.
--
-- Partial UNIQUE index: a seat can have at most one active (i.e.
-- non-dismissed) breadcrumb per paper. Re-breadcrumb after dismiss
-- creates a new row (not an update), so the history is preserved.
-- ====================================================================
create table if not exists breadcrumbs (
  id                    bigserial       primary key,
  seat_id               bigint          not null
                        references seats(id) on delete cascade,
  paper_id              bigint          not null
                        references papers(id) on delete cascade,
  topic_id              bigint          not null
                        references topics(id) on delete cascade,
  created_at            timestamptz     not null default now(),
  dismissed_at          timestamptz     null,
  last_resurface_at     timestamptz     null
);

create unique index if not exists breadcrumbs_active_unique
  on breadcrumbs (seat_id, paper_id)
  where dismissed_at is null;

create index if not exists breadcrumbs_seat_created_idx
  on breadcrumbs (seat_id, created_at);


-- ====================================================================
-- 10. resurface_events · resurface history (O2 source of truth)
-- ====================================================================
-- One row per resurface event. `trigger_type` enum disambiguates
-- the four resurface paths from spec.md §4.2:
--   timed_6wk / timed_3mo / timed_6mo (timed cadence)
--   citation                         (event-driven)
-- `trigger_paper_id` is non-null only for citation triggers (the
-- new paper whose reference list hit the breadcrumb). `context_text`
-- is the system-authored "why now" sentence surfaced to the user.
-- `clicked_at` is set when the user opens the resurface card (O2
-- counter reads this column).
-- ====================================================================
create table if not exists resurface_events (
  id                    bigserial       primary key,
  breadcrumb_id         bigint          not null
                        references breadcrumbs(id) on delete cascade,
  trigger_type          text            not null,
  trigger_paper_id      bigint          null
                        references papers(id) on delete set null,
  context_text          text            not null,
  surfaced_at           timestamptz     not null default now(),
  clicked_at            timestamptz     null,
  dismissed_at          timestamptz     null,

  constraint resurface_trigger_enum
    check (trigger_type in ('timed_6wk', 'timed_3mo', 'timed_6mo', 'citation'))
);

create index if not exists resurface_events_breadcrumb_idx
  on resurface_events (breadcrumb_id, surfaced_at);
create index if not exists resurface_events_surfaced_at_idx
  on resurface_events (surfaced_at);


-- ====================================================================
-- 11. briefings · daily precomputed briefing (one row per topic × date)
-- ====================================================================
-- Written by the 06:00 daily worker (ADR-1, ADR-2). `/today` SSR
-- reads only from this table to meet p95 < 1s. `trigger_paper_ids`
-- embeds the top-3 papers as an array (decision: not a separate
-- `briefing_items` table — architecture.md §5.1 explicitly chose
-- INT[] for simplicity; join overhead is unnecessary at ≤ 15 rows
-- per lab per day). `anchor_paper_id` is the earlier work that
-- state-shift triggered on (null when no shift).
-- ====================================================================
create table if not exists briefings (
  id                    bigserial       primary key,
  lab_id                bigint          not null
                        references labs(id) on delete restrict,
  topic_id              bigint          not null
                        references topics(id) on delete cascade,
  for_date              date            not null,
  state_summary         text            not null,
  -- Ordered; index 0..2 is the display rank. Max 3 per briefing.
  trigger_paper_ids     bigint[]        not null default '{}',
  anchor_paper_id       bigint          null
                        references papers(id) on delete set null,
  llm_provider          text            null, -- audit: which provider assembled
  token_cost_cents      integer         null, -- audit: cost per briefing
  assembled_at          timestamptz     not null default now(),

  constraint briefings_lab_topic_date_uniq unique (lab_id, topic_id, for_date),
  constraint briefings_trigger_paper_cardinality
    check (array_length(trigger_paper_ids, 1) is null
           or array_length(trigger_paper_ids, 1) <= 3)
);

create index if not exists briefings_lab_for_date_idx
  on briefings (lab_id, for_date);


-- ====================================================================
-- 12. fetch_runs · worker run audit (on-boot catchup source)
-- ====================================================================
-- The daily worker writes one row per run. On boot, the worker reads
-- `max(started_at) where status='ok'` and decides whether to catch
-- up (≤ 24h window). `notes` is free-form operator annotation used
-- during debugging and for export compatibility with ops runbook.
-- ====================================================================
create table if not exists fetch_runs (
  id                    bigserial       primary key,
  run_date              date            not null,
  source                text            not null, -- e.g. 'arxiv', 'llm_summary_pass'
  status                text            not null,
  items_fetched         integer         not null default 0,
  started_at            timestamptz     not null default now(),
  finished_at           timestamptz     null,
  error_text            text            null,
  notes                 text            null, -- R1: operator/worker annotation

  constraint fetch_runs_status_enum
    check (status in ('ok', 'failed', 'partial', 'running'))
);

create index if not exists fetch_runs_run_date_source_idx
  on fetch_runs (run_date, source);


-- ====================================================================
-- 13. llm_calls · LLM audit trail (C11 cost envelope; NO response body)
-- ====================================================================
-- Pure audit table. `cost_cents` accumulates toward the C11 $50/mo
-- envelope; worker alerts when monthly sum approaches $40. This
-- table NEVER stores prompt or response text — see ADR-6 for the
-- decision to separate derived data (paper_summaries) from audit.
-- `request_hash` is a sha256 of (prompt_version + input) for dedup
-- checks; duplicate calls within a minute are suspected bugs.
-- ====================================================================
create table if not exists llm_calls (
  id                    bigserial       primary key,
  provider              text            not null,
  model                 text            not null,
  purpose               text            not null, -- 'summarize' | 'judge'
  input_tokens          integer         not null,
  output_tokens         integer         not null,
  cost_cents            integer         not null,
  latency_ms            integer         not null,
  paper_id              bigint          null
                        references papers(id) on delete set null,
  request_hash          text            null,
  called_at             timestamptz     not null default now(),

  constraint llm_calls_purpose_enum
    check (purpose in ('summarize', 'judge'))
);

create index if not exists llm_calls_called_at_idx
  on llm_calls (called_at);
create index if not exists llm_calls_purpose_idx
  on llm_calls (purpose);


-- ====================================================================
-- 14. paper_summaries · LLM-generated ≤ 3-sentence summary (R1 · D15)
-- ====================================================================
-- Derived-data table (distinct from llm_calls audit, see ADR-6).
-- Per (paper × topic × prompt_version) one row. `summary_text` is
-- the rendered ≤ 3-sentence summary shown in briefings. `llm_call_id`
-- FK preserves the audit trail back to the invoking LLM call.
--
-- RED LINE 2 mechanical enforcement (paper_summaries side; D15):
--   `summary_sentence_cap` CHECK counts sentence-terminal punctuation
--   directly (half-width `.!?` + full-width `。！？`) using
--   `regexp_matches(..., 'g')`; asserts 1..3 terminators. Counting
--   terminators (rather than splitting on whitespace) works for pure
--   Chinese text with no whitespace between sentences — the previous
--   split-on-whitespace approach silently passed 5-sentence pure
--   Chinese inputs as a single segment. See risks.md TECH-8 for the
--   corresponding "rejects unterminated text" risk and the
--   application-layer mitigation (`truncateTo3Sentences` in
--   `src/lib/llm/utils.ts` appends `。` defensively).
-- ====================================================================
create table if not exists paper_summaries (
  id                    bigserial       primary key,
  paper_id              bigint          not null
                        references papers(id) on delete cascade,
  topic_id              bigint          not null
                        references topics(id) on delete cascade,
  summary_text          text            not null,
  -- F5 (2026-04-24 · v0.2.2 pre-R_final hardening): llm_call_id is NULLABLE
  -- to support JSON export round-trip (option (a) in api-contracts.md §3.11
  -- Import round-trip notes). Exporter omits llm_calls (audit-internal),
  -- importer defaults to setting this FK to null rather than fabricating
  -- stub llm_calls rows. ON DELETE SET NULL preserves summaries if an
  -- llm_calls row is later purged for audit-retention reasons.
  llm_call_id           bigint          null
                        references llm_calls(id) on delete set null,
  model_name            text            not null,
  prompt_version        text            not null,
  created_at            timestamptz     not null default now(),

  -- RED LINE 2 · D15 (G1 fix 2026-04-24 · R_final B1):
  -- Count sentence-terminal punctuation directly (English `.!?` +
  -- Chinese `。！？`), require 1..3 terminators. The `regexp_matches`
  -- global-flag form returns one row per match; `array_length(...)`
  -- yields the match count. Rejects zero-terminator text (enforces
  -- explicit termination) and >3-terminator text. Whitespace is
  -- irrelevant to the count, so pure Chinese `中文。第二句。第三句。`
  -- (no spaces) is correctly judged as 3 sentences.
  constraint summary_sentence_cap check (
    coalesce(
      array_length(
        regexp_matches(summary_text, '[.!?。！？]', 'g'),
        1
      ),
      0
    ) between 1 and 3
  ),
  -- One summary per (paper, topic, prompt_version); a prompt bump
  -- allows historical summaries under the older version to coexist.
  constraint paper_summaries_unique_key
    unique (paper_id, topic_id, prompt_version)
);

create index if not exists paper_summaries_paper_idx
  on paper_summaries (paper_id);
create index if not exists paper_summaries_topic_idx
  on paper_summaries (topic_id);


-- ====================================================================
-- 15. export_log · JSON export audit (SEC-1; R1 addition)
-- ====================================================================
-- Written every time `/api/export/full` succeeds. `row_counts_jsonb`
-- records row counts of the nine tables included in the export
-- (see architecture.md §8 + T030 grants.sql). Operator performs
-- monthly self-audit (compliance.md §7) reading this table.
-- ====================================================================
create table if not exists export_log (
  id                    bigserial       primary key,
  lab_id                bigint          not null
                        references labs(id) on delete restrict,
  seat_id               bigint          not null
                        references seats(id) on delete restrict,
  export_type           text            not null, -- v0.1 only 'full'
  row_counts_jsonb      jsonb           not null,
  byte_size             integer         not null,
  created_at            timestamptz     not null default now(),

  constraint export_log_type_enum
    check (export_type in ('full'))
);

create index if not exists export_log_lab_created_idx
  on export_log (lab_id, created_at);


-- ====================================================================
-- Bootstrap · seed data for a new lab
-- ====================================================================
-- This bootstrap inserts exactly one lab row. Operator-invited seats
-- (including the operator's own seat) are created via the /admin/invite
-- flow in the UI; we intentionally do NOT seed a hard-coded admin
-- seat so the first-run experience exercises the real invite code path.
-- ====================================================================

-- Default lab row (idempotent). `LAB_DEFAULT_NAME` is read from the
-- application env via scripts/db-seed.ts; this raw SQL uses a
-- literal default. Adjust the literal if running psql directly.
insert into labs (name)
  values ('My Research Lab')
  on conflict do nothing;

-- --------------------------------------------------------------------
-- Example: seed a sample topic (commented out; adjust & uncomment)
-- --------------------------------------------------------------------
-- insert into topics (lab_id, name, keyword_pool, arxiv_categories, seed_authors)
-- values (
--   (select id from labs limit 1),
--   'RLHF alignment',
--   array['RLHF', 'alignment', 'preference learning'],
--   array['cs.LG', 'cs.CL'],
--   array['Christiano Paul F']
-- );


-- ====================================================================
-- End of schema.sql
-- ====================================================================
-- Post-apply checklist:
--   1. `SELECT count(*) FROM information_schema.tables
--         WHERE table_schema = 'public'` should return 15.
--   2. `\d actions` should show `skip_requires_why` CHECK.
--   3. `\d paper_summaries` should show `summary_sentence_cap` CHECK
--         and `paper_summaries_unique_key` UNIQUE.
--   4. `\d labs` should show `first_day_at` (not null) and
--         `allow_continue_until` (nullable).
--   5. `\d seats` should show `invite_token_hash` / `invite_expires_at`
--         / `invited_at` (all nullable).
--   6. `\d sessions` should show `revoked_at` (nullable) and
--         `last_active_at` (not null default now()).
--   7. `SELECT indexname FROM pg_indexes WHERE schemaname = 'public'`
--         should include (non-exhaustive):
--           - actions_seat_created_idx
--           - sessions_seat_login_date_idx
--           - resurface_events_breadcrumb_idx
--           - paper_citations_cited_arxiv_idx
--           - briefings_lab_for_date_idx
--           - paper_summaries_paper_idx
--           - paper_summaries_topic_idx
--           - export_log_lab_created_idx
-- ====================================================================
